PATCH http://localhost:3001/api/admin/technicians/68c7f0be8b4c998ab0bc0175
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOTIzYjAyZTgyNDdmNjAwZDE3MSIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsInNraWxscyI6W10sImlhdCI6MTc1NzkzMzUzMiwiZXhwIjoxNzU4MTkyNzMyfQ.LmdM9AptEO99LvbdwiOf3rRwUb2HxEHMYp2wRw2G-rM
{
    "phone" :"09989637373"
}