GET http://localhost:3000/api/admin/technicians
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmE5MjBkODhmYjVkNzk3NDRhNTUxYiIsIm5hbWUiOiJBZG1pbiAyIiwiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicm9sZSI6IkFkbWluIiwic2tpbGxzIjpbXSwiaWF0IjoxNzUxODE0Njk0LCJleHAiOjE3NTIwNzM4OTR9.E5qz6kriGfyAHrGUMJQLudu6DyxBTECDNjG78e3PRys