POST http://localhost:3001/api/feedback/68cbe2200874d014b3702913
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzY2ZDlmYzk4MTkyNDQwZDllMzBlZCIsIm5hbWUiOiJUZXN0ZXIgMiIsImVtYWlsIjoic2t5MkBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsInNraWxscyI6W10sInBob25lIjoiKzk1OTk4OTYzNzM3MyIsImlhdCI6MTc1ODIwNzYwMiwiZXhwIjoxNzU4NDY2ODAyfQ.3HC5el0mGH7oKk2rqzPeTD1lorOsACXksm4NYYFC-Co
{
  "rating": 4,
  "technicianProfessionalism": "Very professional",
  "serviceSatisfaction": "Satisfied",
  "textReview": "Great service overall!",
  "issueResolved":"Yes"
}
