POST http://localhost:3000/api/feedback/686d0dd70c11986dab47ceb7
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOTU4YjAyZTgyNDdmNjAwZDE3NCIsIm5hbWUiOiJSb3dhbiIsImVtYWlsIjoicm93YW4yOEBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsInNraWxscyI6W10sImlhdCI6MTc1MTk4MTI1OSwiZXhwIjoxNzUyMjQwNDU5fQ.tNGiF7W58lEK7qXobj7p1i7bxYay6VPj8sRo9nJ8o5Q

{
  "rating": 4,
  "technicianProfessionalism": "Very professional",
  "serviceSatisfaction": "Satisfied",
  "textReview": "Great service overall!"
}
