GET http://localhost:3001/api/booking/admin/popular-services
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOTIzYjAyZTgyNDdmNjAwZDE3MSIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsInNraWxscyI6W10sImlhdCI6MTc1ODIwOTYzMSwiZXhwIjoxNzU4NDY4ODMxfQ.BerUNwAVnL2zm8Bc4L1rR-YFNNM7vHD4SU-JbU16kTc