GET http://localhost:3001/api/booking/admin/user-booking-count
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOTIzYjAyZTgyNDdmNjAwZDE3MSIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsInNraWxscyI6W10sImlhdCI6MTc1ODgyNDI1NiwiZXhwIjoxNzU5MDgzNDU2fQ.dKeY8rQRqRItQrA4CQtC_ys6v6SaMbtYu-CI3_OVPE0