GET http://localhost:3001/api/booking/admin/user-booking-count
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOTIzYjAyZTgyNDdmNjAwZDE3MSIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsInNraWxscyI6W10sImlhdCI6MTc1NzI0ODgxOCwiZXhwIjoxNzU3NTA4MDE4fQ.g3MzfwuDFFxboLo9GBWqoTx03ppxJ2PSr3Oo_yDCv7g