GET http://localhost:3001/api/booking/admin/68d5012cbe6e50f0b3cc8d5f
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOTIzYjAyZTgyNDdmNjAwZDE3MSIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW4xQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsInNraWxscyI6W10sImlhdCI6MTc1ODc4MjkyMiwiZXhwIjoxNzU5MDQyMTIyfQ.gEkXkvKU6GNDQpVSPKM908nkRADa_ix7f8WmYxbMNAw