POST http://localhost:3001/api/booking/create
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzQyZGY2ODBlZDJhMmI3ODkwYjMyZCIsIm5hbWUiOiJSb3dhbm5uayIsImVtYWlsIjoicm93YW5ubmtAZ21haWwuY29tIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE3NTc2ODcyODYsImV4cCI6MTc1Nzk0NjQ4Nn0.SOQD6liIqzt9ysJ5A3Td_KVlRBpnnW6nAE4D5sISIfQ
{
  "productModel": "ZKEJEDIJIEJIED",
  "brandName" :"Huawei",
  "serviceType": "Premium",
  "title": "Water leakage issue",
  "description": "Water is leaking from the indoor unit during operation.",
  "photos": [
    "https://example.com/uploads/photo1.jpg",
    "https://example.com/uploads/photo2.jpg"
  ],
  "videos": [
    "https://example.com/uploads/video1.mp4"
  ],
  "bookingDate": "2025-10-07T00:00:00.000Z",
  "timeSlot": "3:00 PM",
  "contactInfo": {
    "name": "Rowan",
    "phone": ["0801234567", "0899876543"],
    "building": "Sunshine Condo",
    "street": "123 Sukhumvit Road",
    "ward": "Wattana",
    "state": "Bangkok"
  }
}
