PATCH http://localhost:3000/booking/6850463bde9a92213751f8a7/service-fee
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGJjYTZjZGRmNmVlOTA4ZWNkY2FmNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obmRvZUBnbWFpbC5jb20iLCJyb2xlIjoiVGVjaG5pY2lhbiIsInNraWxscyI6WyJIVkFDIiwiRWxlY3RyaWNhbCIsIlBsdW1iaW5nIl0sImlhdCI6MTc1MDA5NTY3NiwiZXhwIjoxNzUwMzU0ODc2fQ.GDGA4mXHH3zySlmcD1HXsTUbL5EO2GqmCXILIXscY1Y
{
  "serviceFee": 200000
}