GET http://localhost:3001/api/booking/my-bookings/686d28eed41d4f5475450e48
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOTU4YjAyZTgyNDdmNjAwZDE3NCIsIm5hbWUiOiJSb3dhbiIsImVtYWlsIjoicm93YW4yOEBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsInNraWxscyI6W10sImlhdCI6MTc1NjQ1MTQ3OCwiZXhwIjoxNzU2NzEwNjc4fQ.hFwhqNr6cylFy_vAHoeqg37xLf8ix5o6NyWVYHM2z1c