GET http://localhost:3001/api/booking/user/my-bookings
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzY2ZDlmYzk4MTkyNDQwZDllMzBlZCIsIm5hbWUiOiJUZXN0ZXIgMiIsImVtYWlsIjoic2t5MkBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsInNraWxscyI6W10sInBob25lIjoiKzk1OTk4OTYzNzM3MyIsImlhdCI6MTc1ODE5NDExMywiZXhwIjoxNzU4NDUzMzEzfQ.zrOAEpfSxtWOKvRGpSQkTdl2Q6gAVKEnmzQiJ-6luDU