GET http://localhost:3001/api/booking/technician/by-category
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOWU0YjAyZTgyNDdmNjAwZDE3YyIsIm5hbWUiOiJ0ZWNoMiIsImVtYWlsIjoidGVjaDI0NkBnbWFpbC5jb20iLCJyb2xlIjoiVGVjaG5pY2lhbiIsInNraWxscyI6WyJnYXNfcmVmaWxsIiwiZWxlY3RyaWNhbF9pc3N1ZSIsInBvd2VyX2lzc3VlIl0sImlhdCI6MTc1NjQ1MjYzNCwiZXhwIjoxNzU2NzExODM0fQ.iW6-4IVGr3rHGQd2XQqdEPv3-EWBK7aCYDks9t_SI7I