GET http://localhost:3000/booking/my-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGJkMWNiNmI2OGRiMWE5ZDAyMmYxMSIsIm5hbWUiOiJBZG1pbiAxIiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwicm9sZSI6IkFkbWluIiwic2tpbGxzIjpbXSwiaWF0IjoxNzQ5ODI4NjYzLCJleHAiOjE3NTAwODc4NjN9._T_spdeufyaWftA0YaJ26UrIvhd3xs1P4DqGXvREuKw