GET http://localhost:3000/api/booking/technician/dashboard
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwYTcyYjAyZTgyNDdmNjAwZDE4MCIsIm5hbWUiOiJ0ZWNoMyIsImVtYWlsIjoidGVjaDM1N0BnbWFpbC5jb20iLCJyb2xlIjoiVGVjaG5pY2lhbiIsInNraWxscyI6WyJyZXBhaXIiLCJjbGVhbmluZyIsImluc3RhbGxhdGlvbiJdLCJpYXQiOjE3NTE5ODkyMTQsImV4cCI6MTc1MjI0ODQxNH0.a7suI3tfFuGzAhz3dzUfHhc2JEIHjdYvxX0B2iCDuZw