PATCH http://localhost:3000/api/booking/68977b499ce75c7562d8b368/complete
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwOWU0YjAyZTgyNDdmNjAwZDE3YyIsIm5hbWUiOiJ0ZWNoMiIsImVtYWlsIjoidGVjaDI0NkBnbWFpbC5jb20iLCJyb2xlIjoiVGVjaG5pY2lhbiIsInNraWxscyI6WyJnYXNfcmVmaWxsIiwiZWxlY3RyaWNhbF9pc3N1ZSIsInBvd2VyX2lzc3VlIl0sImlhdCI6MTc1NDc1ODUzMSwiZXhwIjoxNzU1MDE3NzMxfQ.0I_ijBIpqtEAni_4_b0AUoKmzXyZwtkSn-cVZIZFwqQ

{
  "serviceFee": 50000,
  "status": "completed"
}
