PATCH http://localhost:3001/api/booking/68c42eb980ed2a2b7890b339/complete
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmQwYTcyYjAyZTgyNDdmNjAwZDE4MCIsIm5hbWUiOiJ0ZWNoMyIsImVtYWlsIjoidGVjaDM1N0BnbWFpbC5jb20iLCJyb2xlIjoiVGVjaG5pY2lhbiIsInNraWxscyI6WyJyb3V0aW5lX2NsZWFuaW5nIiwiaW5zdGFsbGF0aW9uIiwicmVwYWlyX2FuZF9maXgiLCJvdGhlcl9zZXJ2aWNlcyJdLCJpYXQiOjE3NTc2ODg1NTEsImV4cCI6MTc1Nzk0Nzc1MX0.idE1ANwY4u8B0InYXvFpOPed0atjczvQelfNgxlVetk
{
  "serviceFee": 50000,
  "status": "completed"
}
