GET http://localhost:3001/api/booking/service-history
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzY2YTIxNWU2NTg4MDAxMTkwMzRiMSIsIm5hbWUiOiJQUEEiLCJlbWFpbCI6InNreUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsInNraWxscyI6W10sInBob25lIjoiMDk3NzAxNjM2MzEiLCJpYXQiOjE3NTc5NDMxMjIsImV4cCI6MTc1ODIwMjMyMn0.EobpeU2dYoHiSDL4YoQCf-NbNTn-PUyx2ws5GzH11pE