GET http://localhost:3001/api/booking/service-history
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzQyZGY2ODBlZDJhMmI3ODkwYjMyZCIsIm5hbWUiOiJSb3dhbm5uayIsImVtYWlsIjoicm93YW5ubmtAZ21haWwuY29tIiwicm9sZSI6IlVzZXIiLCJza2lsbHMiOltdLCJpYXQiOjE3NTc2ODc4MzAsImV4cCI6MTc1Nzk0NzAzMH0.AY1ou6QUJ-BwWX8tPA6cShvFEaa_jkkF8BFeK2Zzzls