GET http://localhost:3000/api/booking/service-history
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmE5YzczZjgzNjU0ZDI2Y2I2ZjMwZiIsIm5hbWUiOiJVc2VyMSIsImVtYWlsIjoidXNlcjEyM0BnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsInNraWxscyI6W10sImlhdCI6MTc1MTkwODA4NCwiZXhwIjoxNzUyMTY3Mjg0fQ.QhfgJ-cBu1pU5wY2I0n4TSZcgaitnncuPdBF0LDnRFo
